Adicionando controllers, models e refatorando rotas
UnBArqDsw2021-1/2021.1_G7_Mychine_App pull request #25
Opened 2021-09-28 00:58 UTC by SamuelNoB

2021-09-28 17:33 UTC, EduardoPicolo requested changes

2021-09-28 17:33 UTC, EduardoPicolo commented on .eslintignore
> +#fodase o lint
O que é isso aqui?

2021-09-28 17:34 UTC, SamuelNoB commented on .eslintignore
> +#fodase o lint
@igorq937 a casa caiu!!!!

2021-09-28 19:25 UTC, Matheus73 commented
:bug: Deu muitos conflitos resolvam @SamuelNoB e @giovannabbottino !

2021-09-28 19:42 UTC, EduardoPicolo commented
> bug Deu muitos conflitos resolvam @SamuelNoB e @giovannabbottino !

Resolvidos

2021-09-29 12:44 UTC, Matheus73 approved these changes
Tudo ok ja que os problemas vistos ja foram resolvidos

2021-09-29 12:45 UTC, merged